import mongoose,{Document,Schema} from "mongoose";

export interface IRecipe extends Document {
    mealId:string;
    name:string;
    categoryId:mongoose.Types.ObjectId|null;
    originId:mongoose.Types.ObjectId|null;
    instructions:string|null;
    imageUrl:string|null;
    youtubeUrl:string|null;
    sourceUrl:string|null;
    ingredients:{
        ingredient:string;
        measure:string|null;
    }[];
}

const recipeSchema=new Schema<IRecipe>({
    mealId:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        maxlength:50
    },
    name:{
        type:String,
        required:true,
        trim:true,
        maxlength:255,
        index:true
    },
    categoryId:{
        type:Schema.Types.ObjectId,
        ref:"Category",
        default:null,
        index:true
    },
    originId:{
        type:Schema.Types.ObjectId,
        ref:"Origin",
        default:null,
        index:true
    },
    instructions:{
        type:String,
        default:null
    },
    imageUrl:{
        type:String,
        default:null,
        maxlength:500
    },
    youtubeUrl:{
        type:String,
        default:null,
        maxlength:500
    },
    sourceUrl:{
        type:String,
        default:null,
        maxlength:500
    },
    ingredients:[{
        ingredient:{
            type:String,
            required:true,
            trim:true,
            maxlength:255
        },
        measure:{
            type:String,
            default:null,
            maxlength:100
        }
    }]
});

export const Recipe=mongoose.model<IRecipe>("Recipe",recipeSchema);